logging:
  level.root: INFO
  level.no.fdk: ${LOG_LEVEL:INFO}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
server:
  port: 8080
application:
  scope: ${MASKINPORTEN_SCOPE}
  conceptCatalogBaseURI: ${CONCEPT_CATALOG_BASE_URI}
  databases:
    adminService: catalogAdmin
    conceptCatalog: conceptCatalog
  collections:
    concepts: concepts
    codeLists: codeLists
    editableFields: editableFields
    internalFields: internalFields
    users: catalogUsers
  elastic:
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}
    host: ${ELASTIC_HOST}
    ssl: ${ELASTIC_SSL:true}
    storePath: ${ELASTIC_KEYSTORE_PATH}
    storePass: ${ELASTIC_KEYSTORE_PASSWORD}

spring:
  data.mongodb:
    host: ${MONGODB_HOST}
    username: ${MONGODB_USER}
    password: ${MONGODB_PASSWORD}
    authentication-database: ${MONGODB_AUTH}
    replica-set-name: ${MONGODB_REPLICASET}
    port: 27017
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: ${MASKINPORTEN_JWK:https://test.maskinporten.no/jwk}
    issuer-uri: ${MASKINPORTEN_ISSUER:https://test.maskinporten.no/}
---
spring:
  config.activate.on-profile: develop
  data.mongodb:
    host: localhost
    username: admin
    password: admin
    authentication-database: admin
    replica-set-name: test
  security.oauth2.resourceserver.jwt.jwk-set-uri: https://sso.staging.fellesdatakatalog.digdir.no/auth/realms/fdk/protocol/openid-connect/certs
application:
  scope: test.scope
  elastic:
    username: elastic
    password: elasticpwd
    host: localhost
    ssl: false
---
spring:
  config.activate.on-profile: test
  data.mongodb:
    host: localhost
    username: testuser
    password: testpassword
    authentication-database: admin
    replica-set-name: test
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: http://localhost:5050/jwk
    issuer-uri: http://localhost:5050/
application:
  scope: test.scope
  conceptCatalogBaseURI: http://localhost:5555
  elastic:
    username: elastic
    password: elasticpwd
    ssl: false
    storePass: keystore
