logging:
  level.root: WARN
  level.no.fdk: ${LOG_LEVEL:INFO}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
server:
  port: 8080
application:
  scope: ${MASKINPORTEN_SCOPE}
  conceptCatalogBaseURI: ${CONCEPT_CATALOG_BASE_URI}
  databases:
    adminService: catalogAdminService
    conceptCatalog: concept-catalogue
  collections:
    concepts: begrep
    codeLists: codeLists
    editableFields: editableFields
    internalFields: internalFields
    users: users
  elastic:
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}
    host: ${ELASTIC_HOST}
    ssl: ${ELASTIC_SSL:true}
    storePath: ${ELASTIC_KEYSTORE_PATH}
    storePass: ${ELASTIC_KEYSTORE_PASSWORD}

spring:
  data.mongodb.uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/?authSource=admin&authMechanism=SCRAM-SHA-1
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: ${MASKINPORTEN_JWK:https://test.maskinporten.no/jwk}
    issuer-uri: ${MASKINPORTEN_ISSUER:https://test.maskinporten.no/}
---
spring:
  config.activate.on-profile: test
  data.mongodb.uri: mongodb://admin:admin@localhost:27017/?authSource=admin&authMechanism=SCRAM-SHA-1
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: http://localhost:5050/jwk
    issuer-uri: http://localhost:5050/
application:
  scope: test.scope
  conceptCatalogBaseURI: http://localhost:5555
  elastic:
    username: elastic
    password: elasticpwd
    ssl: false
    storeName: keystore
    storePass: keystore
    certPath: path
