---
apiVersion: v1
kind: Service
metadata:
  name: catalog-view-api
spec:
  selector:
    app: catalog-view-api
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
